### ISSUE TITLE
[QUEST] Crashes the game on startup. 

### ISSUE THREAD

**Issue by Ofacy** [Fernthedev/live_stream_quest#1]
__This is an attempt to install the mod on beat saber version 1.28 using bmbf__:
Installing the mod didn't work properly in the first place, it *"fails to access the file [path to]socket_lib.so"*, I'm assuming this is because the download link for socket_lib in the qmod meta file is a discord cdn link (please avoid doing this, cdn content can be removed at any time).

After manually installing socket_lib from the discord cdn (and forcing it to run on an "incompatible game version" isn't it just a socket library? how is it tied to a game version?), trying to run the game will result in it just **crashing** and no crash report are sent by the crash reporter mod. I wish I had enough knowledge about BS modding to debug this myself and help.

**Comment by Fernthedev** [comment]
If you were able to access the CDN link just fine, I doubt that's the issue.

Anyways try this https://github.com/Fernthedev/live_stream_quest/releases/download/v0.3.3/LiveStream.Quest.qmod

**Comment by Ofacy** [comment]
Hey, install was successful and it did install socket_lib with no issue but the mod isn't loaded on startup.
It doesn't appear in the loaded mods list. (and connection from pc to quest fails)

**Comment by Ofacy** [comment]
Latest pre-release is one commit behind master I think?

**Comment by Fernthedev** [comment]
Woops this one should do the trick https://github.com/Fernthedev/live_stream_quest/releases/tag/v0.3.4

**Comment by Ofacy** [comment]
Looks like it is fixed, it works!

**Comment by Fernthedev** [comment]
Thank you for using and testing this mod! Feel free to report issues or ask for documentation, it's been a bit dusty lately.

Good luck!
